name: quanianitis.com upload blog
  
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["data/**", "public/**"]
  release:
    types: ["published"]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - run: yarn
      - run: yarn build
        env:
          EXPORT: 1
          UNOPTIMIZED: 1
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./out

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-and-upload
    environment: staging
    if: github.event_name == 'push' 
    permissions: # for google creds
      contents: read
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v4'
      - name: Pull artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./out

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'personal-quanianitis'
          workload_identity_provider: 'projects/114204026619/locations/global/workloadIdentityPools/quanianitis/providers/github'

      - id: 'deploy'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: './out'
          destination: 'staging.quanianitis.com'
          parent: false

  deploy-production:
    runs-on: ubuntu-latest
    needs: build-and-upload
    if: github.event_name == 'release' 
    environment: production
    permissions: # for google creds
      contents: read
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v4'
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./out

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'personal-quanianitis'
          workload_identity_provider: 'projects/114204026619/locations/global/workloadIdentityPools/quanianitis/providers/github'

      - id: 'deploy'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: './out'
          destination: 'quanianitis.com'
          parent: false
