name: quanianitis.com upload blog
  
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["data/**", "public/**"]
  release:
    types: ["published"]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions: # for google creds
      contents: read
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - run: yarn
      - run: yarn build
        env:
          EXPORT: 1
          UNOPTIMIZED: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/114204026619/locations/global/workloadIdentityPools/quanianitis/providers/github'

      - id: 'deploy'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        if: github.event_name == 'push' 
        environment: staging
        with:
          path: './out'
          destination: ${{ env.STAGING_URL }}

      - id: 'deploy'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        if: github.event_name == 'release' 
        environment: production
        with:
          path: './out'
          destination: ${{ env.PRODUCTION_URL }}
